engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-5"
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**
exclude_paths:
  - dist/**/*
  - test/**/*
  - examples/
